### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by Juancete** [Fuego1901/FuegoShrek#1]
Hola @Fuego1901 

Ok con la corrección. El código está bien. Solamente un par de observaciones
- faltó la funcionalidad de obtener los nombres de los solicitantes de las misiones. No es más que un map en Shrek.
- (this.nombreDelSolicitante.charAt(0) === 'G') es la expresión booleana. No hace falta meterlo dentro de un if y devolver true. directamente es la expresión en si la que devuelve le true. Por ejemplo si no se cumple no devuelve false en tu caso . 

Saludos!
Juan

**Comment by Fuego1901** [comment]
Hola @Juancete

Ya hice las correcciones mencionadas.

Saludos!

**Comment by Juancete** [comment]
Hola @Fuego1901 

Joyaaaaaaaa!!!! Quedó muy bien. 

Saludos,
Juan
